### ISSUE TITLE
cannot run npm test

### ISSUE THREAD

**Issue by gocepoposki** [gerhardsletten/express-openalpr-server#1]
POST /plates 500 42.657 ms - 156
not ok 1 Error: expected 200 "OK", got 500 "Internal Server Error"
  ---
    operator: fail
    at: Test.api.post.send.expect.expect.end (C:\ogp\express-openalpr-server-master\test\routes.js:29:13)
    stack: |-
      Error: Error: expected 200 "OK", got 500 "Internal Server Error"
          at Test.assert [as _assert] (C:\ogp\express-openalpr-server-master\node_modules\tape\lib\test.js:212:54)
          at Test.bound [as _assert] (C:\ogp\express-openalpr-server-master\node_modules\tape\lib\test.js:64:32)
          at Test.fail (C:\ogp\express-openalpr-server-master\node_modules\tape\lib\test.js:277:10)
          at Test.bound [as fail] (C:\ogp\express-openalpr-server-master\node_modules\tape\lib\test.js:64:32)
          at Test.api.post.send.expect.expect.end (C:\ogp\express-openalpr-server-master\test\routes.js:29:13)
          at Test.assert (C:\ogp\express-openalpr-server-master\node_modules\supertest\lib\test.js:156:6)
          at Server.assert (C:\ogp\express-openalpr-server-master\node_modules\supertest\lib\test.js:127:12)
          at Object.onceWrapper (events.js:293:19)
          at emitNone (events.js:86:13)
          at Server.emit (events.js:188:7)
  ...

**Comment by matass** [comment]
@gocepoposki, you can check my repo (https://github.com/matass/docker-alpr), I will check this routing error

**Comment by gerhardsletten** [comment]
@gocepoposki  There is some time since I wrote this and I currently am not using it myself, so you will need to fork and fix yourself or use @matass version
